/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhiteLabelRouteImport } from './routes/white-label'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as AppTrackedRouteImport } from './routes/app.tracked'
import { Route as AppTelegraphRouteImport } from './routes/app.telegraph'
import { Route as AppStrategiesRouteImport } from './routes/app.strategies'
import { Route as AppSpendRouteImport } from './routes/app.spend'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduledRouteImport } from './routes/app.scheduled'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppModelsRouteImport } from './routes/app.models'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppLandingRouteImport } from './routes/app.landing'
import { Route as AppGraphRouteImport } from './routes/app.graph'
import { Route as AppEditorRouteImport } from './routes/app.editor'
import { Route as AppDmRouteImport } from './routes/app.dm'
import { Route as AppDiscoveryRouteImport } from './routes/app.discovery'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppComposeRouteImport } from './routes/app.compose'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppChannelsRouteImport } from './routes/app.channels'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBotsRouteImport } from './routes/app.bots'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppAdsRouteImport } from './routes/app.ads'
import { Route as AppStrategiesNewRouteImport } from './routes/app.strategies_.new'
import { Route as AppStrategiesIdRouteImport } from './routes/app.strategies_.$id'
import { Route as AppEditorChannelRouteImport } from './routes/app.editor_.$channel'
import { Route as AppDataKeyRouteImport } from './routes/app.data_.$key'
import { Route as AppConnectionsTiktokRouteImport } from './routes/app.connections_.tiktok'
import { Route as AppConnectionsMetaRouteImport } from './routes/app.connections_.meta'
import { Route as AppConnectionsGroupsRouteImport } from './routes/app.connections_.groups'
import { Route as AppChannelsIdRouteImport } from './routes/app.channels_.$id'
import { Route as AppAgentsInboxRouteImport } from './routes/app.agents_.inbox'
import { Route as AppAgentsHandleRouteImport } from './routes/app.agents_.$handle'
import { Route as AppEditorSlotIdRouteImport } from './routes/app.editor_.slot.$id'
import { Route as AppEditorRunIdRouteImport } from './routes/app.editor_.run.$id'
import { Route as AppConnectionsMetaAccountIdRouteImport } from './routes/app.connections_.meta_.$accountId'

const WhiteLabelRoute = WhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackedRoute = AppTrackedRouteImport.update({
  id: '/tracked',
  path: '/tracked',
  getParentRoute: () => AppRoute,
} as any)
const AppTelegraphRoute = AppTelegraphRouteImport.update({
  id: '/telegraph',
  path: '/telegraph',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesRoute = AppStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendRoute = AppSpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduledRoute = AppScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppLandingRoute = AppLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppDmRoute = AppDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsRoute = AppBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsRoute = AppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesNewRoute = AppStrategiesNewRouteImport.update({
  id: '/strategies_/new',
  path: '/strategies/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesIdRoute = AppStrategiesIdRouteImport.update({
  id: '/strategies_/$id',
  path: '/strategies/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorChannelRoute = AppEditorChannelRouteImport.update({
  id: '/editor_/$channel',
  path: '/editor/$channel',
  getParentRoute: () => AppRoute,
} as any)
const AppDataKeyRoute = AppDataKeyRouteImport.update({
  id: '/data_/$key',
  path: '/data/$key',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsTiktokRoute = AppConnectionsTiktokRouteImport.update({
  id: '/connections_/tiktok',
  path: '/connections/tiktok',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsMetaRoute = AppConnectionsMetaRouteImport.update({
  id: '/connections_/meta',
  path: '/connections/meta',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsGroupsRoute = AppConnectionsGroupsRouteImport.update({
  id: '/connections_/groups',
  path: '/connections/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsIdRoute = AppChannelsIdRouteImport.update({
  id: '/channels_/$id',
  path: '/channels/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsInboxRoute = AppAgentsInboxRouteImport.update({
  id: '/agents_/inbox',
  path: '/agents/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsHandleRoute = AppAgentsHandleRouteImport.update({
  id: '/agents_/$handle',
  path: '/agents/$handle',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorSlotIdRoute = AppEditorSlotIdRouteImport.update({
  id: '/editor_/slot/$id',
  path: '/editor/slot/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRunIdRoute = AppEditorRunIdRouteImport.update({
  id: '/editor_/run/$id',
  path: '/editor/run/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsMetaAccountIdRoute =
  AppConnectionsMetaAccountIdRouteImport.update({
    id: '/connections_/meta_/$accountId',
    path: '/connections/meta/$accountId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/white-label': typeof WhiteLabelRoute
  '/app/ads': typeof AppAdsRoute
  '/app/agent': typeof AppAgentRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bots': typeof AppBotsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/chat': typeof AppChatRoute
  '/app/compose': typeof AppComposeRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/data': typeof AppDataRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/dm': typeof AppDmRoute
  '/app/editor': typeof AppEditorRoute
  '/app/graph': typeof AppGraphRoute
  '/app/landing': typeof AppLandingRoute
  '/app/logs': typeof AppLogsRoute
  '/app/models': typeof AppModelsRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/scheduled': typeof AppScheduledRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spend': typeof AppSpendRoute
  '/app/strategies': typeof AppStrategiesRoute
  '/app/telegraph': typeof AppTelegraphRoute
  '/app/tracked': typeof AppTrackedRoute
  '/report/$token': typeof ReportTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$handle': typeof AppAgentsHandleRoute
  '/app/agents/inbox': typeof AppAgentsInboxRoute
  '/app/channels/$id': typeof AppChannelsIdRoute
  '/app/connections/groups': typeof AppConnectionsGroupsRoute
  '/app/connections/meta': typeof AppConnectionsMetaRoute
  '/app/connections/tiktok': typeof AppConnectionsTiktokRoute
  '/app/data/$key': typeof AppDataKeyRoute
  '/app/editor/$channel': typeof AppEditorChannelRoute
  '/app/strategies/$id': typeof AppStrategiesIdRoute
  '/app/strategies/new': typeof AppStrategiesNewRoute
  '/app/connections/meta/$accountId': typeof AppConnectionsMetaAccountIdRoute
  '/app/editor/run/$id': typeof AppEditorRunIdRoute
  '/app/editor/slot/$id': typeof AppEditorSlotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/white-label': typeof WhiteLabelRoute
  '/app/ads': typeof AppAdsRoute
  '/app/agent': typeof AppAgentRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bots': typeof AppBotsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/chat': typeof AppChatRoute
  '/app/compose': typeof AppComposeRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/data': typeof AppDataRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/dm': typeof AppDmRoute
  '/app/editor': typeof AppEditorRoute
  '/app/graph': typeof AppGraphRoute
  '/app/landing': typeof AppLandingRoute
  '/app/logs': typeof AppLogsRoute
  '/app/models': typeof AppModelsRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/scheduled': typeof AppScheduledRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spend': typeof AppSpendRoute
  '/app/strategies': typeof AppStrategiesRoute
  '/app/telegraph': typeof AppTelegraphRoute
  '/app/tracked': typeof AppTrackedRoute
  '/report/$token': typeof ReportTokenRoute
  '/app': typeof AppIndexRoute
  '/app/agents/$handle': typeof AppAgentsHandleRoute
  '/app/agents/inbox': typeof AppAgentsInboxRoute
  '/app/channels/$id': typeof AppChannelsIdRoute
  '/app/connections/groups': typeof AppConnectionsGroupsRoute
  '/app/connections/meta': typeof AppConnectionsMetaRoute
  '/app/connections/tiktok': typeof AppConnectionsTiktokRoute
  '/app/data/$key': typeof AppDataKeyRoute
  '/app/editor/$channel': typeof AppEditorChannelRoute
  '/app/strategies/$id': typeof AppStrategiesIdRoute
  '/app/strategies/new': typeof AppStrategiesNewRoute
  '/app/connections/meta/$accountId': typeof AppConnectionsMetaAccountIdRoute
  '/app/editor/run/$id': typeof AppEditorRunIdRoute
  '/app/editor/slot/$id': typeof AppEditorSlotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/white-label': typeof WhiteLabelRoute
  '/app/ads': typeof AppAdsRoute
  '/app/agent': typeof AppAgentRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bots': typeof AppBotsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/chat': typeof AppChatRoute
  '/app/compose': typeof AppComposeRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/data': typeof AppDataRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/dm': typeof AppDmRoute
  '/app/editor': typeof AppEditorRoute
  '/app/graph': typeof AppGraphRoute
  '/app/landing': typeof AppLandingRoute
  '/app/logs': typeof AppLogsRoute
  '/app/models': typeof AppModelsRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/scheduled': typeof AppScheduledRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spend': typeof AppSpendRoute
  '/app/strategies': typeof AppStrategiesRoute
  '/app/telegraph': typeof AppTelegraphRoute
  '/app/tracked': typeof AppTrackedRoute
  '/report/$token': typeof ReportTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/agents_/$handle': typeof AppAgentsHandleRoute
  '/app/agents_/inbox': typeof AppAgentsInboxRoute
  '/app/channels_/$id': typeof AppChannelsIdRoute
  '/app/connections_/groups': typeof AppConnectionsGroupsRoute
  '/app/connections_/meta': typeof AppConnectionsMetaRoute
  '/app/connections_/tiktok': typeof AppConnectionsTiktokRoute
  '/app/data_/$key': typeof AppDataKeyRoute
  '/app/editor_/$channel': typeof AppEditorChannelRoute
  '/app/strategies_/$id': typeof AppStrategiesIdRoute
  '/app/strategies_/new': typeof AppStrategiesNewRoute
  '/app/connections_/meta_/$accountId': typeof AppConnectionsMetaAccountIdRoute
  '/app/editor_/run/$id': typeof AppEditorRunIdRoute
  '/app/editor_/slot/$id': typeof AppEditorSlotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/white-label'
    | '/app/ads'
    | '/app/agent'
    | '/app/agents'
    | '/app/analytics'
    | '/app/bots'
    | '/app/calendar'
    | '/app/channels'
    | '/app/chat'
    | '/app/compose'
    | '/app/connections'
    | '/app/data'
    | '/app/discovery'
    | '/app/dm'
    | '/app/editor'
    | '/app/graph'
    | '/app/landing'
    | '/app/logs'
    | '/app/models'
    | '/app/recommendations'
    | '/app/scheduled'
    | '/app/settings'
    | '/app/spend'
    | '/app/strategies'
    | '/app/telegraph'
    | '/app/tracked'
    | '/report/$token'
    | '/app/'
    | '/app/agents/$handle'
    | '/app/agents/inbox'
    | '/app/channels/$id'
    | '/app/connections/groups'
    | '/app/connections/meta'
    | '/app/connections/tiktok'
    | '/app/data/$key'
    | '/app/editor/$channel'
    | '/app/strategies/$id'
    | '/app/strategies/new'
    | '/app/connections/meta/$accountId'
    | '/app/editor/run/$id'
    | '/app/editor/slot/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/white-label'
    | '/app/ads'
    | '/app/agent'
    | '/app/agents'
    | '/app/analytics'
    | '/app/bots'
    | '/app/calendar'
    | '/app/channels'
    | '/app/chat'
    | '/app/compose'
    | '/app/connections'
    | '/app/data'
    | '/app/discovery'
    | '/app/dm'
    | '/app/editor'
    | '/app/graph'
    | '/app/landing'
    | '/app/logs'
    | '/app/models'
    | '/app/recommendations'
    | '/app/scheduled'
    | '/app/settings'
    | '/app/spend'
    | '/app/strategies'
    | '/app/telegraph'
    | '/app/tracked'
    | '/report/$token'
    | '/app'
    | '/app/agents/$handle'
    | '/app/agents/inbox'
    | '/app/channels/$id'
    | '/app/connections/groups'
    | '/app/connections/meta'
    | '/app/connections/tiktok'
    | '/app/data/$key'
    | '/app/editor/$channel'
    | '/app/strategies/$id'
    | '/app/strategies/new'
    | '/app/connections/meta/$accountId'
    | '/app/editor/run/$id'
    | '/app/editor/slot/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/white-label'
    | '/app/ads'
    | '/app/agent'
    | '/app/agents'
    | '/app/analytics'
    | '/app/bots'
    | '/app/calendar'
    | '/app/channels'
    | '/app/chat'
    | '/app/compose'
    | '/app/connections'
    | '/app/data'
    | '/app/discovery'
    | '/app/dm'
    | '/app/editor'
    | '/app/graph'
    | '/app/landing'
    | '/app/logs'
    | '/app/models'
    | '/app/recommendations'
    | '/app/scheduled'
    | '/app/settings'
    | '/app/spend'
    | '/app/strategies'
    | '/app/telegraph'
    | '/app/tracked'
    | '/report/$token'
    | '/app/'
    | '/app/agents_/$handle'
    | '/app/agents_/inbox'
    | '/app/channels_/$id'
    | '/app/connections_/groups'
    | '/app/connections_/meta'
    | '/app/connections_/tiktok'
    | '/app/data_/$key'
    | '/app/editor_/$channel'
    | '/app/strategies_/$id'
    | '/app/strategies_/new'
    | '/app/connections_/meta_/$accountId'
    | '/app/editor_/run/$id'
    | '/app/editor_/slot/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WhiteLabelRoute: typeof WhiteLabelRoute
  ReportTokenRoute: typeof ReportTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/white-label': {
      id: '/white-label'
      path: '/white-label'
      fullPath: '/white-label'
      preLoaderRoute: typeof WhiteLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tracked': {
      id: '/app/tracked'
      path: '/tracked'
      fullPath: '/app/tracked'
      preLoaderRoute: typeof AppTrackedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/telegraph': {
      id: '/app/telegraph'
      path: '/telegraph'
      fullPath: '/app/telegraph'
      preLoaderRoute: typeof AppTelegraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strategies': {
      id: '/app/strategies'
      path: '/strategies'
      fullPath: '/app/strategies'
      preLoaderRoute: typeof AppStrategiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spend': {
      id: '/app/spend'
      path: '/spend'
      fullPath: '/app/spend'
      preLoaderRoute: typeof AppSpendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scheduled': {
      id: '/app/scheduled'
      path: '/scheduled'
      fullPath: '/app/scheduled'
      preLoaderRoute: typeof AppScheduledRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/landing': {
      id: '/app/landing'
      path: '/landing'
      fullPath: '/app/landing'
      preLoaderRoute: typeof AppLandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/graph': {
      id: '/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dm': {
      id: '/app/dm'
      path: '/dm'
      fullPath: '/app/dm'
      preLoaderRoute: typeof AppDmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discovery': {
      id: '/app/discovery'
      path: '/discovery'
      fullPath: '/app/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compose': {
      id: '/app/compose'
      path: '/compose'
      fullPath: '/app/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels': {
      id: '/app/channels'
      path: '/channels'
      fullPath: '/app/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bots': {
      id: '/app/bots'
      path: '/bots'
      fullPath: '/app/bots'
      preLoaderRoute: typeof AppBotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ads': {
      id: '/app/ads'
      path: '/ads'
      fullPath: '/app/ads'
      preLoaderRoute: typeof AppAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strategies_/new': {
      id: '/app/strategies_/new'
      path: '/strategies/new'
      fullPath: '/app/strategies/new'
      preLoaderRoute: typeof AppStrategiesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strategies_/$id': {
      id: '/app/strategies_/$id'
      path: '/strategies/$id'
      fullPath: '/app/strategies/$id'
      preLoaderRoute: typeof AppStrategiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor_/$channel': {
      id: '/app/editor_/$channel'
      path: '/editor/$channel'
      fullPath: '/app/editor/$channel'
      preLoaderRoute: typeof AppEditorChannelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data_/$key': {
      id: '/app/data_/$key'
      path: '/data/$key'
      fullPath: '/app/data/$key'
      preLoaderRoute: typeof AppDataKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections_/tiktok': {
      id: '/app/connections_/tiktok'
      path: '/connections/tiktok'
      fullPath: '/app/connections/tiktok'
      preLoaderRoute: typeof AppConnectionsTiktokRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections_/meta': {
      id: '/app/connections_/meta'
      path: '/connections/meta'
      fullPath: '/app/connections/meta'
      preLoaderRoute: typeof AppConnectionsMetaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections_/groups': {
      id: '/app/connections_/groups'
      path: '/connections/groups'
      fullPath: '/app/connections/groups'
      preLoaderRoute: typeof AppConnectionsGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels_/$id': {
      id: '/app/channels_/$id'
      path: '/channels/$id'
      fullPath: '/app/channels/$id'
      preLoaderRoute: typeof AppChannelsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents_/inbox': {
      id: '/app/agents_/inbox'
      path: '/agents/inbox'
      fullPath: '/app/agents/inbox'
      preLoaderRoute: typeof AppAgentsInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents_/$handle': {
      id: '/app/agents_/$handle'
      path: '/agents/$handle'
      fullPath: '/app/agents/$handle'
      preLoaderRoute: typeof AppAgentsHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor_/slot/$id': {
      id: '/app/editor_/slot/$id'
      path: '/editor/slot/$id'
      fullPath: '/app/editor/slot/$id'
      preLoaderRoute: typeof AppEditorSlotIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor_/run/$id': {
      id: '/app/editor_/run/$id'
      path: '/editor/run/$id'
      fullPath: '/app/editor/run/$id'
      preLoaderRoute: typeof AppEditorRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections_/meta_/$accountId': {
      id: '/app/connections_/meta_/$accountId'
      path: '/connections/meta/$accountId'
      fullPath: '/app/connections/meta/$accountId'
      preLoaderRoute: typeof AppConnectionsMetaAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdsRoute: typeof AppAdsRoute
  AppAgentRoute: typeof AppAgentRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBotsRoute: typeof AppBotsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppChatRoute: typeof AppChatRoute
  AppComposeRoute: typeof AppComposeRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppDataRoute: typeof AppDataRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppDmRoute: typeof AppDmRoute
  AppEditorRoute: typeof AppEditorRoute
  AppGraphRoute: typeof AppGraphRoute
  AppLandingRoute: typeof AppLandingRoute
  AppLogsRoute: typeof AppLogsRoute
  AppModelsRoute: typeof AppModelsRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppScheduledRoute: typeof AppScheduledRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpendRoute: typeof AppSpendRoute
  AppStrategiesRoute: typeof AppStrategiesRoute
  AppTelegraphRoute: typeof AppTelegraphRoute
  AppTrackedRoute: typeof AppTrackedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsHandleRoute: typeof AppAgentsHandleRoute
  AppAgentsInboxRoute: typeof AppAgentsInboxRoute
  AppChannelsIdRoute: typeof AppChannelsIdRoute
  AppConnectionsGroupsRoute: typeof AppConnectionsGroupsRoute
  AppConnectionsMetaRoute: typeof AppConnectionsMetaRoute
  AppConnectionsTiktokRoute: typeof AppConnectionsTiktokRoute
  AppDataKeyRoute: typeof AppDataKeyRoute
  AppEditorChannelRoute: typeof AppEditorChannelRoute
  AppStrategiesIdRoute: typeof AppStrategiesIdRoute
  AppStrategiesNewRoute: typeof AppStrategiesNewRoute
  AppConnectionsMetaAccountIdRoute: typeof AppConnectionsMetaAccountIdRoute
  AppEditorRunIdRoute: typeof AppEditorRunIdRoute
  AppEditorSlotIdRoute: typeof AppEditorSlotIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdsRoute: AppAdsRoute,
  AppAgentRoute: AppAgentRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBotsRoute: AppBotsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppChatRoute: AppChatRoute,
  AppComposeRoute: AppComposeRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppDataRoute: AppDataRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppDmRoute: AppDmRoute,
  AppEditorRoute: AppEditorRoute,
  AppGraphRoute: AppGraphRoute,
  AppLandingRoute: AppLandingRoute,
  AppLogsRoute: AppLogsRoute,
  AppModelsRoute: AppModelsRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppScheduledRoute: AppScheduledRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpendRoute: AppSpendRoute,
  AppStrategiesRoute: AppStrategiesRoute,
  AppTelegraphRoute: AppTelegraphRoute,
  AppTrackedRoute: AppTrackedRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentsHandleRoute: AppAgentsHandleRoute,
  AppAgentsInboxRoute: AppAgentsInboxRoute,
  AppChannelsIdRoute: AppChannelsIdRoute,
  AppConnectionsGroupsRoute: AppConnectionsGroupsRoute,
  AppConnectionsMetaRoute: AppConnectionsMetaRoute,
  AppConnectionsTiktokRoute: AppConnectionsTiktokRoute,
  AppDataKeyRoute: AppDataKeyRoute,
  AppEditorChannelRoute: AppEditorChannelRoute,
  AppStrategiesIdRoute: AppStrategiesIdRoute,
  AppStrategiesNewRoute: AppStrategiesNewRoute,
  AppConnectionsMetaAccountIdRoute: AppConnectionsMetaAccountIdRoute,
  AppEditorRunIdRoute: AppEditorRunIdRoute,
  AppEditorSlotIdRoute: AppEditorSlotIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WhiteLabelRoute: WhiteLabelRoute,
  ReportTokenRoute: ReportTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
