/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackedRouteImport } from './routes/tracked'
import { Route as TelegraphRouteImport } from './routes/telegraph'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionsTiktokRouteImport } from './routes/connections_.tiktok'
import { Route as ConnectionsMetaRouteImport } from './routes/connections_.meta'
import { Route as ConnectionsPlatformRouteImport } from './routes/connections.$platform'
import { Route as ChannelsIdRouteImport } from './routes/channels_.$id'
import { Route as ConnectionsMetaAccountIdRouteImport } from './routes/connections_.meta_.$accountId'

const TrackedRoute = TrackedRouteImport.update({
  id: '/tracked',
  path: '/tracked',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegraphRoute = TelegraphRouteImport.update({
  id: '/telegraph',
  path: '/telegraph',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsTiktokRoute = ConnectionsTiktokRouteImport.update({
  id: '/connections_/tiktok',
  path: '/connections/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsMetaRoute = ConnectionsMetaRouteImport.update({
  id: '/connections_/meta',
  path: '/connections/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsPlatformRoute = ConnectionsPlatformRouteImport.update({
  id: '/$platform',
  path: '/$platform',
  getParentRoute: () => ConnectionsRoute,
} as any)
const ChannelsIdRoute = ChannelsIdRouteImport.update({
  id: '/channels_/$id',
  path: '/channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsMetaAccountIdRoute =
  ConnectionsMetaAccountIdRouteImport.update({
    id: '/connections_/meta_/$accountId',
    path: '/connections/meta/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bots': typeof BotsRoute
  '/calendar': typeof CalendarRoute
  '/channels': typeof ChannelsRoute
  '/compose': typeof ComposeRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/recommendations': typeof RecommendationsRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/strategies': typeof StrategiesRoute
  '/telegraph': typeof TelegraphRoute
  '/tracked': typeof TrackedRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/connections/$platform': typeof ConnectionsPlatformRoute
  '/connections/meta': typeof ConnectionsMetaRoute
  '/connections/tiktok': typeof ConnectionsTiktokRoute
  '/connections/meta/$accountId': typeof ConnectionsMetaAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bots': typeof BotsRoute
  '/calendar': typeof CalendarRoute
  '/channels': typeof ChannelsRoute
  '/compose': typeof ComposeRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/recommendations': typeof RecommendationsRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/strategies': typeof StrategiesRoute
  '/telegraph': typeof TelegraphRoute
  '/tracked': typeof TrackedRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/connections/$platform': typeof ConnectionsPlatformRoute
  '/connections/meta': typeof ConnectionsMetaRoute
  '/connections/tiktok': typeof ConnectionsTiktokRoute
  '/connections/meta/$accountId': typeof ConnectionsMetaAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bots': typeof BotsRoute
  '/calendar': typeof CalendarRoute
  '/channels': typeof ChannelsRoute
  '/compose': typeof ComposeRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/recommendations': typeof RecommendationsRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/strategies': typeof StrategiesRoute
  '/telegraph': typeof TelegraphRoute
  '/tracked': typeof TrackedRoute
  '/channels_/$id': typeof ChannelsIdRoute
  '/connections/$platform': typeof ConnectionsPlatformRoute
  '/connections_/meta': typeof ConnectionsMetaRoute
  '/connections_/tiktok': typeof ConnectionsTiktokRoute
  '/connections_/meta_/$accountId': typeof ConnectionsMetaAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bots'
    | '/calendar'
    | '/channels'
    | '/compose'
    | '/connections'
    | '/discovery'
    | '/graph'
    | '/login'
    | '/logs'
    | '/recommendations'
    | '/scheduled'
    | '/settings'
    | '/strategies'
    | '/telegraph'
    | '/tracked'
    | '/channels/$id'
    | '/connections/$platform'
    | '/connections/meta'
    | '/connections/tiktok'
    | '/connections/meta/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bots'
    | '/calendar'
    | '/channels'
    | '/compose'
    | '/connections'
    | '/discovery'
    | '/graph'
    | '/login'
    | '/logs'
    | '/recommendations'
    | '/scheduled'
    | '/settings'
    | '/strategies'
    | '/telegraph'
    | '/tracked'
    | '/channels/$id'
    | '/connections/$platform'
    | '/connections/meta'
    | '/connections/tiktok'
    | '/connections/meta/$accountId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bots'
    | '/calendar'
    | '/channels'
    | '/compose'
    | '/connections'
    | '/discovery'
    | '/graph'
    | '/login'
    | '/logs'
    | '/recommendations'
    | '/scheduled'
    | '/settings'
    | '/strategies'
    | '/telegraph'
    | '/tracked'
    | '/channels_/$id'
    | '/connections/$platform'
    | '/connections_/meta'
    | '/connections_/tiktok'
    | '/connections_/meta_/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BotsRoute: typeof BotsRoute
  CalendarRoute: typeof CalendarRoute
  ChannelsRoute: typeof ChannelsRoute
  ComposeRoute: typeof ComposeRoute
  ConnectionsRoute: typeof ConnectionsRouteWithChildren
  DiscoveryRoute: typeof DiscoveryRoute
  GraphRoute: typeof GraphRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ScheduledRoute: typeof ScheduledRoute
  SettingsRoute: typeof SettingsRoute
  StrategiesRoute: typeof StrategiesRoute
  TelegraphRoute: typeof TelegraphRoute
  TrackedRoute: typeof TrackedRoute
  ChannelsIdRoute: typeof ChannelsIdRoute
  ConnectionsMetaRoute: typeof ConnectionsMetaRoute
  ConnectionsTiktokRoute: typeof ConnectionsTiktokRoute
  ConnectionsMetaAccountIdRoute: typeof ConnectionsMetaAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracked': {
      id: '/tracked'
      path: '/tracked'
      fullPath: '/tracked'
      preLoaderRoute: typeof TrackedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegraph': {
      id: '/telegraph'
      path: '/telegraph'
      fullPath: '/telegraph'
      preLoaderRoute: typeof TelegraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections_/tiktok': {
      id: '/connections_/tiktok'
      path: '/connections/tiktok'
      fullPath: '/connections/tiktok'
      preLoaderRoute: typeof ConnectionsTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections_/meta': {
      id: '/connections_/meta'
      path: '/connections/meta'
      fullPath: '/connections/meta'
      preLoaderRoute: typeof ConnectionsMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$platform': {
      id: '/connections/$platform'
      path: '/$platform'
      fullPath: '/connections/$platform'
      preLoaderRoute: typeof ConnectionsPlatformRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/channels_/$id': {
      id: '/channels_/$id'
      path: '/channels/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof ChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections_/meta_/$accountId': {
      id: '/connections_/meta_/$accountId'
      path: '/connections/meta/$accountId'
      fullPath: '/connections/meta/$accountId'
      preLoaderRoute: typeof ConnectionsMetaAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConnectionsRouteChildren {
  ConnectionsPlatformRoute: typeof ConnectionsPlatformRoute
}

const ConnectionsRouteChildren: ConnectionsRouteChildren = {
  ConnectionsPlatformRoute: ConnectionsPlatformRoute,
}

const ConnectionsRouteWithChildren = ConnectionsRoute._addFileChildren(
  ConnectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BotsRoute: BotsRoute,
  CalendarRoute: CalendarRoute,
  ChannelsRoute: ChannelsRoute,
  ComposeRoute: ComposeRoute,
  ConnectionsRoute: ConnectionsRouteWithChildren,
  DiscoveryRoute: DiscoveryRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  RecommendationsRoute: RecommendationsRoute,
  ScheduledRoute: ScheduledRoute,
  SettingsRoute: SettingsRoute,
  StrategiesRoute: StrategiesRoute,
  TelegraphRoute: TelegraphRoute,
  TrackedRoute: TrackedRoute,
  ChannelsIdRoute: ChannelsIdRoute,
  ConnectionsMetaRoute: ConnectionsMetaRoute,
  ConnectionsTiktokRoute: ConnectionsTiktokRoute,
  ConnectionsMetaAccountIdRoute: ConnectionsMetaAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
