/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsIdRouteImport } from './routes/channels_.$id'

const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIdRoute = ChannelsIdRouteImport.update({
  id: '/channels_/$id',
  path: '/channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/channels': typeof ChannelsRoute
  '/discovery': typeof DiscoveryRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/strategies': typeof StrategiesRoute
  '/channels/$id': typeof ChannelsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/channels': typeof ChannelsRoute
  '/discovery': typeof DiscoveryRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/strategies': typeof StrategiesRoute
  '/channels/$id': typeof ChannelsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/channels': typeof ChannelsRoute
  '/discovery': typeof DiscoveryRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/strategies': typeof StrategiesRoute
  '/channels_/$id': typeof ChannelsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/channels'
    | '/discovery'
    | '/graph'
    | '/login'
    | '/recommendations'
    | '/strategies'
    | '/channels/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/channels'
    | '/discovery'
    | '/graph'
    | '/login'
    | '/recommendations'
    | '/strategies'
    | '/channels/$id'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/channels'
    | '/discovery'
    | '/graph'
    | '/login'
    | '/recommendations'
    | '/strategies'
    | '/channels_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRoute: typeof BotsRoute
  ChannelsRoute: typeof ChannelsRoute
  DiscoveryRoute: typeof DiscoveryRoute
  GraphRoute: typeof GraphRoute
  LoginRoute: typeof LoginRoute
  RecommendationsRoute: typeof RecommendationsRoute
  StrategiesRoute: typeof StrategiesRoute
  ChannelsIdRoute: typeof ChannelsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels_/$id': {
      id: '/channels_/$id'
      path: '/channels/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof ChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRoute: BotsRoute,
  ChannelsRoute: ChannelsRoute,
  DiscoveryRoute: DiscoveryRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  RecommendationsRoute: RecommendationsRoute,
  StrategiesRoute: StrategiesRoute,
  ChannelsIdRoute: ChannelsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
